### ISSUE TITLE
is there any example about android?

### ISSUE THREAD

**Issue by yanghuxiao** [carbon-native/carbon-native#1]
is it support for android,i can't find any example about android platform.

**Comment by tylerbuchea** [comment]
Android compatibility is next on our list. Should have something up for you relatively soon @yanghuxiao

**Comment by yanghuxiao** [comment]
It's a good job.I wait for yor new version.thank you very much for reply.

**Comment by joshbuchea** [comment]
@yanghuxiao Just released version 0.1.0 with support for Android :tada:
