### ISSUE TITLE
Google Play App no longer found

### ISSUE THREAD

**Issue by JakeHadley** [carbon-native/carbon-native#14]
Is this repo still maintained? I can't get any of the demo apps to work.

**Comment by tylerbuchea** [comment]
Will check into this weekend @pianoman730 thanks for the heads up.

**Comment by tylerbuchea** [comment]
We decided not to keep maintaining the app store apps, but the Kitchen Sink will always be available on Expo https://expo.io/@tylerbuchea/carbon-native-kitchen-sink
