### ISSUE TITLE
ToolbarLeft or ToolbarRight can't work in RN 0.26

### ISSUE THREAD

**Issue by PeterRock** [carbon-native/carbon-native#3]
It noticed that ToolbarLeft is undefined.
So,I changed this:
Form import View from React-Native

Before:
`
export default function ToolbarRight(props) {
  return (
    <Container
      {...props}
....
    >
      {props.children}
    </Container>
  );
}
`
I paste the code from container.js, then it's like
`
export default function ToolbarRight(props) {
  return (
    <View style={[cs.container, props.padding && cs.padding, props.style]}>
      <View
        ...
      </View>
     </View>
`
It worked!
Maybe it's RN's new bug

**Comment by tylerbuchea** [comment]
Good find peter I left you a message in PR #2 I will definitely accept your changes for this. Just submit a new PR with only `Make the ToolbarLeft/Right available` & `Yes, I forgot to add View from react-native`.

I'll close this as soon as we merge that new PR from you. Thanks again Peter, you Rock ;)
